### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/cheque#1]
I am trying to get TB with Panda running under PHP 7.3. Things aren't going very well.

One thing I regularly encounter (and I may even have seen under 7.1) is this error:
  Warning on line 66 of /modules/cheque/cheque.php
  [2] count: Parameter must be an array or an object that implements Countable

The cheque module is present but not installed.
The picture is from Performance page, But I have also seen it on the Modules page and the Position-a-module page and likely more. But its doesn't appear always. After I have changed some settings it sometimes stops appearing - only to reappear after a few more changes.

The issue may be Windows related.
![upgrade1](https://user-images.githubusercontent.com/13930107/68552117-cd17cc00-0413-11ea-92f4-249cf9d6fab9.jpg)

**Comment by getdatakick** [comment]
Could not reproduce. The error message does not look like coming from tb cheque module - there's no `count` operation on line 66.
